spring.application.name=mealmap-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/mealmapdb
spring.datasource.username=mealmap
spring.datasource.password=mealmap

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true